name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        # run tests here

    - name: Trigger Jenkins job
      if: success()
      uses: jenkins-actions/jenkins-action@v1
      with:
        url: http://3.138.122.101:8080
        job: git integration
        token: ${{ secrets.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 }}
