name: Jenkins Integration
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Trigger Jenkins Job
      run:  http://52.14.62.107:8080/job/git integration/ --user admin:${{ secrets.JENKINSTOKEN }}
